// <auto-generated />
using StationApiExercise.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StationApiExercise.Migrations
{
    [DbContext(typeof(StationDbContext))]
    partial class StationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("StationApiExercise.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationUicOrPart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StationUicOrPart = 127
                        },
                        new
                        {
                            Id = 2,
                            StationUicOrPart = 325
                        },
                        new
                        {
                            Id = 3,
                            StationUicOrPart = 8600109
                        },
                        new
                        {
                            Id = 4,
                            StationUicOrPart = 8600810
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
